name: Deploy Images to GHCR

on:
  push:
    branches:
      - docker-mod
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
      push-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v4
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build --no-cache . --tag ghcr.io/intro-skipper/intro-skipper-docker-mod:latest
              docker push ghcr.io/intro-skipper/intro-skipper-docker-mod:latest
